`ifndef SALARAS_RX_DEFS_SVH
`define SALARAS_RX_DEFS_SVH

`define SRX_HEADER_BITS      96
`define SRX_PAYLOAD_BITS     96
`define SRX_PAYLOAD_DATA_BITS 72
`define SRX_INTEGRITY_BITS   24

`define SRX_HALF_PERIOD      9
`define SRX_QUARTER_PERIOD   4
`define SRX_TIMING_TOLERANCE 2
`define SRX_TIMEOUT_CYCLES   4096

`define SRX_PREAMBLE         32'hAAAAAAAA
`define SRX_TYPE_WORD        16'hD391
`define SRX_CONSTANT_WORD    32'h0DFFFFFE

`define SRX_CRC_POLY         24'h864CFB
`define SRX_CRC_INIT         24'hB704CE

`endif
