name: lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verilator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator

      - name: Lint RTL
        run: make lint
